platform :ios, '12'
install! 'cocoapods', :deterministic_uuids => false, :warn_for_unused_master_specs_repo => false

inhibit_all_warnings!

use_frameworks! 
plugin 'cocoapods-keys', {
  :project => "greenTravel",
  :keys => [
    "Environment",
    "NativeClientUrl",
    "NativeClientImageUrl",
    "NativeClientGraphQLUrl",
    "NativeClientGraphQLApiKey",
    "MapAccessToken",
    "MapBoxClientUrl",
    "MapBoxStyleUrlAny",
    "MapBoxStyleUrlDark",
    "AmplitudeKey",
    "MapboxDownloadsToken",
    "NativeClientIndexFileBaseUrl",
]}

target 'greenTravel' do
  pod 'Firebase/AnalyticsWithoutAdIdSupport'
  # add pods for any other desired Firebase products
  # https://firebase.google.com/docs/ios/setup#available-pods
  pod 'Firebase/Crashlytics'
  pod 'Firebase/Performance'
  pod 'Amplitude', '~> 8.2.0'
  pod 'Mapbox-iOS-SDK', '~> 6.4.1'
  
  pod 'Amplify'
  pod 'AmplifyPlugins/AWSCognitoAuthPlugin'
  pod 'SDWebImage', '~> 5.0'

  pod 'SwiftLint'

  

  post_install do |installer|

#     __apply_Xcode_12_5_M1_post_install_workaround(installer)
#     installer.pods_project.targets.each do |target|
#       target.build_configurations.each do |config|
#         config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
#         config.build_settings.delete 'ARCHS'
#       end
#     end
#
#     installer.pods_project.targets.each do |target|
#       if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle"
#         target.build_configurations.each do |config|
#             config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
#         end
#       end
#     end
  end
end
